name: movie_list_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  #add your dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 #app icon generator

flutter:
  fonts:
    - family: Lota Grotesque
      fonts:
        - asset: assets/fonts/lota-grotesque-font-family/LotaGrotesqueAlt3-Bold.otf
        - asset: assets/fonts/lota-grotesque-font-family/LotaGrotesqueAlt3-Light.otf
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: 'assets/images/icon.png' #change this to your app icon then run 'dart run flutter_launcher_icons'
  android: true
  ios: true
